In [3]:
from math import sqrt
import numpy as np

# Decomposição de Cholesky 

Dada **A** $\in M(n,n)$ SPD. Queremos **H** $\in M(n, n)$, tal que:

$$A = H . H^T$$

[![https://imgur.com/uXRuTxz.png](https://imgur.com/uXRuTxz.png)](https://imgur.com/uXRuTxz.png)



1. Diagonal 
$$h_{i i} = \left( a_{ii} - \sum_{k = 1}^{i - 1} h_{i k}^2\right)^{\frac{1}{2}}$$

2. Fora da diagonal 

$$ h_{i j} = \frac{a_{i j} - \sum_{k = 1}^{j - 1} h_{i k} h_{j k}} {h_{j j}}$$



## Complexidade: 

 **Cholesky:** $\frac{n^3}{3}$ flops
  - $50 \%$ mais eficiente que LU!
  - Economia de memória, pois só armazena uma matriz!


In [4]:
def cholesky(A):
    n = np.shape(A)[0]
    H = np.zeros((n,n))

    for i in np.arange(n):
        for j in np.arange(i + 1):
            tmp_sum = sum(H[i][k] * H[j][k] for k in np.arange(j))           
            if (i == j):
                H[i][j] = sqrt(A[i][i] - tmp_sum)
            else:
                H[i][j] = ((A[i][j] - tmp_sum) / H[j][j])
    return H

## Exemplo

In [5]:
A = [[3,2,0], [2,5,1], [0,1,3]]
H = cholesky(A)

print(f"Matrix Original: \n{np.array(A)}")
print("\n\n")
print(f"Matrix Cholesky: \n {H}")

Matrix Original: 
[[3 2 0]
 [2 5 1]
 [0 1 3]]



Matrix Cholesky: 
 [[1.73205081 0.         0.        ]
 [1.15470054 1.91485422 0.        ]
 [0.         0.52223297 1.65144565]]
