In [1]:
import numpy as np
import sympy

# Decomposição LU


Dada $A \in M(n,n)$. Queremos **L, U** $\in M(n,n)$, tal que:

$$A = L U$$



[![https://imgur.com/MR6sECM.png](https://imgur.com/MR6sECM.png)](https://imgur.com/MR6sECM.png)

**Sua Decomposição:**

[![https://imgur.com/JQLK2X6.png](https://imgur.com/JQLK2X6.png)](https://imgur.com/JQLK2X6.png)



## Termos Gerais 


$$u_{i j} = a_{i j} - \sum_{k = 1}^{i-1} l_{i k} u_{k j}$$

$$l_{i j} = \frac{a_{i j} -  \sum_{k = 1}^{j-1} l_{i k } u_{k j}}{u_{jj}}$$



## Complexidade: 

- **LU:** $\frac{2n^3}{3}$ flops


In [2]:
def decompLU(A):
    n = np.shape(A)[0]
    L = np.eye(n) 
    U = np.zeros((n,n))
    
    for k  in np.arange(n):
        for j in np.arange(k,n):
            U[k,j] = A[k, j]
            for s in np.arange(k):
                U[k, j] = U[k, j] - L[k, s] * U[s, j]
        for i in np.arange(k + 1, n):  ### Pq esse intervalo? 
            L[i, k] = A[i, k]
            for s in np.arange(k):
                L[i, k] = L[i, k] - L[i, s] * U[s, k]
            L[i, k] = L[i, k] / U[k, k]
    return L, U  

## LU Solve


Sabendo que:

[![https://imgur.com/jvfFjF2.png](https://imgur.com/jvfFjF2.png)](https://imgur.com/jvfFjF2.png)

Como resolver $Ax = b$ com $b = [2, 1, 4]^T$?


**Solução:**

[![https://imgur.com/LA3MYje.png](https://imgur.com/LA3MYje.png)](https://imgur.com/LA3MYje.png)

1. Resolva $L y = b$ com substituições progressivas 
2. Resolva $U x = y$ com substituições regressivas



In [3]:
def LUsolve(A, b):
    n = np.shape(A)[0]  
    L, U = decompLU(A)
    for k in range(1, n):
        b[k] = b[k] - L[k, 0:k].dot(b[0:k])
    for k in range(n - 1, -1 , -1):
        b[k] = (b[k] - U[k, k + 1:n].dot(b[k + 1:n])) / U[k, k]
    return b

## Exemplo 


In [4]:
A = np.array([[1, 2,0], [1, 3,1],[-2, 0,1]])
b = np.array([3,5,-1])

L, U = decompLU(A)

x = LUsolve(A,b)


print(f"L: {L}")
print(f"U: {U}")
print(f"Solução x: {x}")

L: [[ 1.  0.  0.]
 [ 1.  1.  0.]
 [-2.  4.  1.]]
U: [[ 1.  2.  0.]
 [ 0.  1.  1.]
 [ 0.  0. -3.]]
Solução x: [1 1 1]


## Com a biblioteca python3

In [5]:
#Decomposição LU com SymPy

A = sympy.Matrix([[1, 2,0], [1, 3,1],[-2, 0,1] ])
b = sympy.Matrix([3, 5,-1])
L, U, _ = A.LUdecomposition()


print(f"L: {L}")
print(f"U: {U}")

x = A.solve(b); 
print(f"Solução: {x}")

L: Matrix([[1, 0, 0], [1, 1, 0], [-2, 4, 1]])
U: Matrix([[1, 2, 0], [0, 1, 1], [0, 0, -3]])
Solução: Matrix([[1], [1], [1]])
